name: Raúl Diaz
description: SW Architect
theme: jekyll-theme-cayman
avatar: "raul_diaz_avatar.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true
